name: Blob storage website CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    
    - name: Run Az CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name paco7input7data -d '$web' -s .
